{{- if and .Values.gateway.enabled .Values.admin.enabled }}
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayParameters
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  rawConfig:
    config:
      adminAddr: {{ printf "0.0.0.0:%d" (int .Values.admin.port) | quote }}
{{- end }}
