apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: agentgateway
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.monitoring.enabled }}
  monitor:
    - selector:
        app.kubernetes.io/name: agentgateway
      targetPort: 9092
      portName: metrics
      path: /metrics
      kind: ServiceMonitor
      description: Metrics scraping for Agentgateway controller
  {{- end }}

  network:
    serviceMesh:
      mode: ambient
    expose:
      {{- if .Values.admin.enabled }}
      - service: agentgateway-admin
        selector:
          {{ .Values.gateway.podLabelKey }}: {{ .Values.gateway.name }}
        gateway: admin
        host: {{ .Values.admin.host }}
        port: {{ .Values.admin.port }}
        targetPort: {{ .Values.admin.port }}
        description: "Agentgateway Admin UI"
      {{- end }}
      {{- if .Values.mcp.enabled }}
      - service: {{ .Values.gateway.name }}
        selector:
          {{ .Values.gateway.podLabelKey }}: {{ .Values.gateway.name }}
        gateway: tenant
        host: {{ .Values.mcp.host }}
        port: {{ .Values.mcp.port }}
        targetPort: {{ .Values.mcp.port }}
        description: "Agentgateway MCP endpoint"
      {{- end }}
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: IntraNamespace

      - direction: Egress
        selector:
          app.kubernetes.io/name: agentgateway
        remoteGenerated: KubeAPI
        description: "Agentgateway controller to Kube API for Gateway API discovery"

      {{- with .Values.additionalNetworkAllow }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
